//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.ServiceVol {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostaEvoRequest", Namespace="http://comunicazionielettroniche.posteitaliane.it/postaevo/data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.ConfermaInvioRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.RecuperaDocumentoRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.RecuperaServizioRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.RecuperaStatoRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.InvioRequest))]
    public partial class PostaEvoRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfermaInvioRequest", Namespace="http://comunicazionielettroniche.posteitaliane.it/camerali/data")]
    [System.SerializableAttribute()]
    public partial class ConfermaInvioRequest : Api.ServiceVol.PostaEvoRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdRichiestaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdRichiesta {
            get {
                return this.IdRichiestaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdRichiestaField, value) != true)) {
                    this.IdRichiestaField = value;
                    this.RaisePropertyChanged("IdRichiesta");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecuperaDocumentoRequest", Namespace="http://comunicazionielettroniche.posteitaliane.it/camerali/data")]
    [System.SerializableAttribute()]
    public partial class RecuperaDocumentoRequest : Api.ServiceVol.PostaEvoRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdRichiestaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdRichiesta {
            get {
                return this.IdRichiestaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdRichiestaField, value) != true)) {
                    this.IdRichiestaField = value;
                    this.RaisePropertyChanged("IdRichiesta");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecuperaServizioRequest", Namespace="http://comunicazionielettroniche.posteitaliane.it/camerali/data")]
    [System.SerializableAttribute()]
    public partial class RecuperaServizioRequest : Api.ServiceVol.PostaEvoRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodiceDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodiceFiscaleIntestatarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CognomeIntestatarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataConfermaRichiestaAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataConfermaRichiestaDaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataInvioRichiestaAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataInvioRichiestaDaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] IdRichiesteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeIntestatarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NumeroElementiPerPaginaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NumeroPaginaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroREAIntestatarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OggettoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RagioneSocialeIntestatarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatoLavorazioneField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodiceDocumento {
            get {
                return this.CodiceDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodiceDocumentoField, value) != true)) {
                    this.CodiceDocumentoField = value;
                    this.RaisePropertyChanged("CodiceDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodiceFiscaleIntestatario {
            get {
                return this.CodiceFiscaleIntestatarioField;
            }
            set {
                if ((object.ReferenceEquals(this.CodiceFiscaleIntestatarioField, value) != true)) {
                    this.CodiceFiscaleIntestatarioField = value;
                    this.RaisePropertyChanged("CodiceFiscaleIntestatario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CognomeIntestatario {
            get {
                return this.CognomeIntestatarioField;
            }
            set {
                if ((object.ReferenceEquals(this.CognomeIntestatarioField, value) != true)) {
                    this.CognomeIntestatarioField = value;
                    this.RaisePropertyChanged("CognomeIntestatario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataConfermaRichiestaA {
            get {
                return this.DataConfermaRichiestaAField;
            }
            set {
                if ((this.DataConfermaRichiestaAField.Equals(value) != true)) {
                    this.DataConfermaRichiestaAField = value;
                    this.RaisePropertyChanged("DataConfermaRichiestaA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataConfermaRichiestaDa {
            get {
                return this.DataConfermaRichiestaDaField;
            }
            set {
                if ((this.DataConfermaRichiestaDaField.Equals(value) != true)) {
                    this.DataConfermaRichiestaDaField = value;
                    this.RaisePropertyChanged("DataConfermaRichiestaDa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataInvioRichiestaA {
            get {
                return this.DataInvioRichiestaAField;
            }
            set {
                if ((this.DataInvioRichiestaAField.Equals(value) != true)) {
                    this.DataInvioRichiestaAField = value;
                    this.RaisePropertyChanged("DataInvioRichiestaA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataInvioRichiestaDa {
            get {
                return this.DataInvioRichiestaDaField;
            }
            set {
                if ((this.DataInvioRichiestaDaField.Equals(value) != true)) {
                    this.DataInvioRichiestaDaField = value;
                    this.RaisePropertyChanged("DataInvioRichiestaDa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] IdRichieste {
            get {
                return this.IdRichiesteField;
            }
            set {
                if ((object.ReferenceEquals(this.IdRichiesteField, value) != true)) {
                    this.IdRichiesteField = value;
                    this.RaisePropertyChanged("IdRichieste");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeIntestatario {
            get {
                return this.NomeIntestatarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeIntestatarioField, value) != true)) {
                    this.NomeIntestatarioField = value;
                    this.RaisePropertyChanged("NomeIntestatario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Note {
            get {
                return this.NoteField;
            }
            set {
                if ((object.ReferenceEquals(this.NoteField, value) != true)) {
                    this.NoteField = value;
                    this.RaisePropertyChanged("Note");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumeroElementiPerPagina {
            get {
                return this.NumeroElementiPerPaginaField;
            }
            set {
                if ((this.NumeroElementiPerPaginaField.Equals(value) != true)) {
                    this.NumeroElementiPerPaginaField = value;
                    this.RaisePropertyChanged("NumeroElementiPerPagina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumeroPagina {
            get {
                return this.NumeroPaginaField;
            }
            set {
                if ((this.NumeroPaginaField.Equals(value) != true)) {
                    this.NumeroPaginaField = value;
                    this.RaisePropertyChanged("NumeroPagina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroREAIntestatario {
            get {
                return this.NumeroREAIntestatarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroREAIntestatarioField, value) != true)) {
                    this.NumeroREAIntestatarioField = value;
                    this.RaisePropertyChanged("NumeroREAIntestatario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Oggetto {
            get {
                return this.OggettoField;
            }
            set {
                if ((object.ReferenceEquals(this.OggettoField, value) != true)) {
                    this.OggettoField = value;
                    this.RaisePropertyChanged("Oggetto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RagioneSocialeIntestatario {
            get {
                return this.RagioneSocialeIntestatarioField;
            }
            set {
                if ((object.ReferenceEquals(this.RagioneSocialeIntestatarioField, value) != true)) {
                    this.RagioneSocialeIntestatarioField = value;
                    this.RaisePropertyChanged("RagioneSocialeIntestatario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatoLavorazione {
            get {
                return this.StatoLavorazioneField;
            }
            set {
                if ((object.ReferenceEquals(this.StatoLavorazioneField, value) != true)) {
                    this.StatoLavorazioneField = value;
                    this.RaisePropertyChanged("StatoLavorazione");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecuperaStatoRequest", Namespace="http://comunicazionielettroniche.posteitaliane.it/camerali/data")]
    [System.SerializableAttribute()]
    public partial class RecuperaStatoRequest : Api.ServiceVol.PostaEvoRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] IdRichiestaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] IdRichiesta {
            get {
                return this.IdRichiestaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdRichiestaField, value) != true)) {
                    this.IdRichiestaField = value;
                    this.RaisePropertyChanged("IdRichiesta");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvioRequest", Namespace="http://comunicazionielettroniche.posteitaliane.it/camerali/data")]
    [System.SerializableAttribute()]
    public partial class InvioRequest : Api.ServiceVol.PostaEvoRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Api.ServiceVol.DatiOpzionali DatiOpzionaliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Api.ServiceVol.Destinatario DestinatarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Api.ServiceVol.Documento DocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Api.ServiceVol.Richiedente RichiedenteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Api.ServiceVol.DatiOpzionali DatiOpzionali {
            get {
                return this.DatiOpzionaliField;
            }
            set {
                if ((object.ReferenceEquals(this.DatiOpzionaliField, value) != true)) {
                    this.DatiOpzionaliField = value;
                    this.RaisePropertyChanged("DatiOpzionali");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Api.ServiceVol.Destinatario Destinatario {
            get {
                return this.DestinatarioField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinatarioField, value) != true)) {
                    this.DestinatarioField = value;
                    this.RaisePropertyChanged("Destinatario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Api.ServiceVol.Documento Documento {
            get {
                return this.DocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoField, value) != true)) {
                    this.DocumentoField = value;
                    this.RaisePropertyChanged("Documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Api.ServiceVol.Richiedente Richiedente {
            get {
                return this.RichiedenteField;
            }
            set {
                if ((object.ReferenceEquals(this.RichiedenteField, value) != true)) {
                    this.RichiedenteField = value;
                    this.RaisePropertyChanged("Richiedente");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatiOpzionali", Namespace="http://comunicazionielettroniche.posteitaliane.it/camerali/data")]
    [System.SerializableAttribute()]
    public partial class DatiOpzionali : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CentroCostoClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OggettoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CentroCostoCliente {
            get {
                return this.CentroCostoClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.CentroCostoClienteField, value) != true)) {
                    this.CentroCostoClienteField = value;
                    this.RaisePropertyChanged("CentroCostoCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Note {
            get {
                return this.NoteField;
            }
            set {
                if ((object.ReferenceEquals(this.NoteField, value) != true)) {
                    this.NoteField = value;
                    this.RaisePropertyChanged("Note");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Oggetto {
            get {
                return this.OggettoField;
            }
            set {
                if ((object.ReferenceEquals(this.OggettoField, value) != true)) {
                    this.OggettoField = value;
                    this.RaisePropertyChanged("Oggetto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Destinatario", Namespace="http://comunicazionielettroniche.posteitaliane.it/camerali/data")]
    [System.SerializableAttribute()]
    public partial class Destinatario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CAPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IndirizzoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalitaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NominativoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Api.ServiceVol.TipoRecapito TipoRecapitoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CAP {
            get {
                return this.CAPField;
            }
            set {
                if ((object.ReferenceEquals(this.CAPField, value) != true)) {
                    this.CAPField = value;
                    this.RaisePropertyChanged("CAP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Indirizzo {
            get {
                return this.IndirizzoField;
            }
            set {
                if ((object.ReferenceEquals(this.IndirizzoField, value) != true)) {
                    this.IndirizzoField = value;
                    this.RaisePropertyChanged("Indirizzo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Localita {
            get {
                return this.LocalitaField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalitaField, value) != true)) {
                    this.LocalitaField = value;
                    this.RaisePropertyChanged("Localita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nominativo {
            get {
                return this.NominativoField;
            }
            set {
                if ((object.ReferenceEquals(this.NominativoField, value) != true)) {
                    this.NominativoField = value;
                    this.RaisePropertyChanged("Nominativo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Api.ServiceVol.TipoRecapito TipoRecapito {
            get {
                return this.TipoRecapitoField;
            }
            set {
                if ((this.TipoRecapitoField.Equals(value) != true)) {
                    this.TipoRecapitoField = value;
                    this.RaisePropertyChanged("TipoRecapito");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Documento", Namespace="http://comunicazionielettroniche.posteitaliane.it/camerali/data")]
    [System.SerializableAttribute()]
    public partial class Documento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BolloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChiusuraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Api.ServiceVol.CodiceDocumento CodiceDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<Api.ServiceVol.Formato> FormatoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Api.ServiceVol.Intestatario IntestatarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Api.ServiceVol.TipoDocumento TipoDocumentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Bollo {
            get {
                return this.BolloField;
            }
            set {
                if ((this.BolloField.Equals(value) != true)) {
                    this.BolloField = value;
                    this.RaisePropertyChanged("Bollo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Chiusura {
            get {
                return this.ChiusuraField;
            }
            set {
                if ((object.ReferenceEquals(this.ChiusuraField, value) != true)) {
                    this.ChiusuraField = value;
                    this.RaisePropertyChanged("Chiusura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Api.ServiceVol.CodiceDocumento CodiceDocumento {
            get {
                return this.CodiceDocumentoField;
            }
            set {
                if ((this.CodiceDocumentoField.Equals(value) != true)) {
                    this.CodiceDocumentoField = value;
                    this.RaisePropertyChanged("CodiceDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<Api.ServiceVol.Formato> Formato {
            get {
                return this.FormatoField;
            }
            set {
                if ((this.FormatoField.Equals(value) != true)) {
                    this.FormatoField = value;
                    this.RaisePropertyChanged("Formato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Api.ServiceVol.Intestatario Intestatario {
            get {
                return this.IntestatarioField;
            }
            set {
                if ((object.ReferenceEquals(this.IntestatarioField, value) != true)) {
                    this.IntestatarioField = value;
                    this.RaisePropertyChanged("Intestatario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Api.ServiceVol.TipoDocumento TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((this.TipoDocumentoField.Equals(value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Richiedente", Namespace="http://comunicazionielettroniche.posteitaliane.it/camerali/data")]
    [System.SerializableAttribute()]
    public partial class Richiedente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CAPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CognomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IndirizzoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalitaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CAP {
            get {
                return this.CAPField;
            }
            set {
                if ((object.ReferenceEquals(this.CAPField, value) != true)) {
                    this.CAPField = value;
                    this.RaisePropertyChanged("CAP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cognome {
            get {
                return this.CognomeField;
            }
            set {
                if ((object.ReferenceEquals(this.CognomeField, value) != true)) {
                    this.CognomeField = value;
                    this.RaisePropertyChanged("Cognome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Indirizzo {
            get {
                return this.IndirizzoField;
            }
            set {
                if ((object.ReferenceEquals(this.IndirizzoField, value) != true)) {
                    this.IndirizzoField = value;
                    this.RaisePropertyChanged("Indirizzo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Localita {
            get {
                return this.LocalitaField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalitaField, value) != true)) {
                    this.LocalitaField = value;
                    this.RaisePropertyChanged("Localita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoRecapito", Namespace="http://comunicazionielettroniche.posteitaliane.it/camerali/data")]
    public enum TipoRecapito : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        S = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        E = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        D = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        P = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Intestatario", Namespace="http://comunicazionielettroniche.posteitaliane/camerali/data")]
    [System.SerializableAttribute()]
    public partial class Intestatario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CCIAAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CognomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DatoFiscaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NREAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RagioneSocialeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CCIAA {
            get {
                return this.CCIAAField;
            }
            set {
                if ((object.ReferenceEquals(this.CCIAAField, value) != true)) {
                    this.CCIAAField = value;
                    this.RaisePropertyChanged("CCIAA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cognome {
            get {
                return this.CognomeField;
            }
            set {
                if ((object.ReferenceEquals(this.CognomeField, value) != true)) {
                    this.CognomeField = value;
                    this.RaisePropertyChanged("Cognome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DatoFiscale {
            get {
                return this.DatoFiscaleField;
            }
            set {
                if ((object.ReferenceEquals(this.DatoFiscaleField, value) != true)) {
                    this.DatoFiscaleField = value;
                    this.RaisePropertyChanged("DatoFiscale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NREA {
            get {
                return this.NREAField;
            }
            set {
                if ((this.NREAField.Equals(value) != true)) {
                    this.NREAField = value;
                    this.RaisePropertyChanged("NREA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RagioneSociale {
            get {
                return this.RagioneSocialeField;
            }
            set {
                if ((object.ReferenceEquals(this.RagioneSocialeField, value) != true)) {
                    this.RagioneSocialeField = value;
                    this.RaisePropertyChanged("RagioneSociale");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CodiceDocumento", Namespace="http://comunicazionielettroniche.posteitaliane.it/camerali/data")]
    public enum CodiceDocumento : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CART = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CRIA = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CRIM = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CRIS = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ATTI = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BICM = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FASC = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RIPR = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SCPE = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SCSC = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SCSO = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SOST = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TRSF = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VISO = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VISS = 14,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Formato", Namespace="http://comunicazionielettroniche.posteitaliane.it/camerali/data")]
    public enum Formato : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XML = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PDF = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoDocumento", Namespace="http://comunicazionielettroniche.posteitaliane.it/camerali/data")]
    public enum TipoDocumento : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CertificatoCamerale = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VisuraCamerale = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostaEvoResponse", Namespace="http://comunicazionielettroniche.posteitaliane.it/postaevo/data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.ConfermaInvioResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.RecuperaDocumentoResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.RecuperaServizioResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.RecuperaStatoResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.InvioResponse))]
    public partial class PostaEvoResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Api.ServiceVol.ErrorePostaEvo[] ErroriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Api.ServiceVol.EsitoPostaEvo EsitoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Api.ServiceVol.ErrorePostaEvo[] Errori {
            get {
                return this.ErroriField;
            }
            set {
                if ((object.ReferenceEquals(this.ErroriField, value) != true)) {
                    this.ErroriField = value;
                    this.RaisePropertyChanged("Errori");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Api.ServiceVol.EsitoPostaEvo Esito {
            get {
                return this.EsitoField;
            }
            set {
                if ((this.EsitoField.Equals(value) != true)) {
                    this.EsitoField = value;
                    this.RaisePropertyChanged("Esito");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfermaInvioResponse", Namespace="http://comunicazionielettroniche.posteitaliane.it/camerali/data")]
    [System.SerializableAttribute()]
    public partial class ConfermaInvioResponse : Api.ServiceVol.PostaEvoResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataAccettazioneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdTicketField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataAccettazione {
            get {
                return this.DataAccettazioneField;
            }
            set {
                if ((this.DataAccettazioneField.Equals(value) != true)) {
                    this.DataAccettazioneField = value;
                    this.RaisePropertyChanged("DataAccettazione");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdTicket {
            get {
                return this.IdTicketField;
            }
            set {
                if ((object.ReferenceEquals(this.IdTicketField, value) != true)) {
                    this.IdTicketField = value;
                    this.RaisePropertyChanged("IdTicket");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecuperaDocumentoResponse", Namespace="http://comunicazionielettroniche.posteitaliane.it/camerali/data")]
    [System.SerializableAttribute()]
    public partial class RecuperaDocumentoResponse : Api.ServiceVol.PostaEvoResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Api.ServiceVol.Documento1 DocumentoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Api.ServiceVol.Documento1 Documento {
            get {
                return this.DocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoField, value) != true)) {
                    this.DocumentoField = value;
                    this.RaisePropertyChanged("Documento");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecuperaServizioResponse", Namespace="http://comunicazionielettroniche.posteitaliane.it/camerali/data")]
    [System.SerializableAttribute()]
    public partial class RecuperaServizioResponse : Api.ServiceVol.PostaEvoResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroPaginaCorrenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroTotaleElementiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroTotalePagineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Api.ServiceVol.Servizio[] ServiziField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroPaginaCorrente {
            get {
                return this.NumeroPaginaCorrenteField;
            }
            set {
                if ((this.NumeroPaginaCorrenteField.Equals(value) != true)) {
                    this.NumeroPaginaCorrenteField = value;
                    this.RaisePropertyChanged("NumeroPaginaCorrente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroTotaleElementi {
            get {
                return this.NumeroTotaleElementiField;
            }
            set {
                if ((this.NumeroTotaleElementiField.Equals(value) != true)) {
                    this.NumeroTotaleElementiField = value;
                    this.RaisePropertyChanged("NumeroTotaleElementi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroTotalePagine {
            get {
                return this.NumeroTotalePagineField;
            }
            set {
                if ((this.NumeroTotalePagineField.Equals(value) != true)) {
                    this.NumeroTotalePagineField = value;
                    this.RaisePropertyChanged("NumeroTotalePagine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Api.ServiceVol.Servizio[] Servizi {
            get {
                return this.ServiziField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiziField, value) != true)) {
                    this.ServiziField = value;
                    this.RaisePropertyChanged("Servizi");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecuperaStatoResponse", Namespace="http://comunicazionielettroniche.posteitaliane.it/camerali/data")]
    [System.SerializableAttribute()]
    public partial class RecuperaStatoResponse : Api.ServiceVol.PostaEvoResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Api.ServiceVol.StatoRichiesta[] StatiRichiesteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Api.ServiceVol.StatoRichiesta[] StatiRichieste {
            get {
                return this.StatiRichiesteField;
            }
            set {
                if ((object.ReferenceEquals(this.StatiRichiesteField, value) != true)) {
                    this.StatiRichiesteField = value;
                    this.RaisePropertyChanged("StatiRichieste");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvioResponse", Namespace="http://comunicazionielettroniche.posteitaliane.it/camerali/data")]
    [System.SerializableAttribute()]
    public partial class InvioResponse : Api.ServiceVol.PostaEvoResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Api.ServiceVol.DatiIntestatarioValidati DatiIntestatarioValidatiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Api.ServiceVol.DatiOpzionali DatiOpzionaliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Api.ServiceVol.Destinatario DestinatarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Api.ServiceVol.Documento DocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdRichiestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdTicketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Api.ServiceVol.Richiedente RichiedenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Api.ServiceVol.ValorizzazioneServizio ValorizzazioneField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Api.ServiceVol.DatiIntestatarioValidati DatiIntestatarioValidati {
            get {
                return this.DatiIntestatarioValidatiField;
            }
            set {
                if ((object.ReferenceEquals(this.DatiIntestatarioValidatiField, value) != true)) {
                    this.DatiIntestatarioValidatiField = value;
                    this.RaisePropertyChanged("DatiIntestatarioValidati");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Api.ServiceVol.DatiOpzionali DatiOpzionali {
            get {
                return this.DatiOpzionaliField;
            }
            set {
                if ((object.ReferenceEquals(this.DatiOpzionaliField, value) != true)) {
                    this.DatiOpzionaliField = value;
                    this.RaisePropertyChanged("DatiOpzionali");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Api.ServiceVol.Destinatario Destinatario {
            get {
                return this.DestinatarioField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinatarioField, value) != true)) {
                    this.DestinatarioField = value;
                    this.RaisePropertyChanged("Destinatario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Api.ServiceVol.Documento Documento {
            get {
                return this.DocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoField, value) != true)) {
                    this.DocumentoField = value;
                    this.RaisePropertyChanged("Documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdRichiesta {
            get {
                return this.IdRichiestaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdRichiestaField, value) != true)) {
                    this.IdRichiestaField = value;
                    this.RaisePropertyChanged("IdRichiesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdTicket {
            get {
                return this.IdTicketField;
            }
            set {
                if ((object.ReferenceEquals(this.IdTicketField, value) != true)) {
                    this.IdTicketField = value;
                    this.RaisePropertyChanged("IdTicket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Api.ServiceVol.Richiedente Richiedente {
            get {
                return this.RichiedenteField;
            }
            set {
                if ((object.ReferenceEquals(this.RichiedenteField, value) != true)) {
                    this.RichiedenteField = value;
                    this.RaisePropertyChanged("Richiedente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Api.ServiceVol.ValorizzazioneServizio Valorizzazione {
            get {
                return this.ValorizzazioneField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorizzazioneField, value) != true)) {
                    this.ValorizzazioneField = value;
                    this.RaisePropertyChanged("Valorizzazione");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorePostaEvo", Namespace="http://comunicazionielettroniche.posteitaliane.it/postaevo/data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.InvioRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.DatiOpzionali))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.Destinatario))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.TipoRecapito))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.Documento))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.CodiceDocumento))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.Formato))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.TipoDocumento))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.Richiedente))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.InvioResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.DatiIntestatarioValidati))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.ValorizzazioneServizio))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.ConfermaInvioRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.ConfermaInvioResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.RecuperaDocumentoRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.RecuperaDocumentoResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.RecuperaServizioRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.RecuperaServizioResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.Servizio[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.Servizio))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.RecuperaStatoRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.RecuperaStatoResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.StatoRichiesta[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.StatoRichiesta))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.PostaEvoRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.PostaEvoResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.ErrorePostaEvo[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.EsitoPostaEvo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.ProdottoAmministrativo[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.ProdottoAmministrativo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.Documento1))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.ServiceVol.Intestatario))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
    public partial class ErrorePostaEvo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object MessaggioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codice {
            get {
                return this.CodiceField;
            }
            set {
                if ((this.CodiceField.Equals(value) != true)) {
                    this.CodiceField = value;
                    this.RaisePropertyChanged("Codice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Messaggio {
            get {
                return this.MessaggioField;
            }
            set {
                if ((object.ReferenceEquals(this.MessaggioField, value) != true)) {
                    this.MessaggioField = value;
                    this.RaisePropertyChanged("Messaggio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EsitoPostaEvo", Namespace="http://comunicazionielettroniche.posteitaliane.it/postaevo/data")]
    public enum EsitoPostaEvo : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KO = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatiIntestatarioValidati", Namespace="http://comunicazionielettroniche.posteitaliane.it/camerali/data")]
    [System.SerializableAttribute()]
    public partial class DatiIntestatarioValidati : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CCIAAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodiceFiscaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CognomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataDiNascitaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NREAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RagioneSocialeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CCIAA {
            get {
                return this.CCIAAField;
            }
            set {
                if ((object.ReferenceEquals(this.CCIAAField, value) != true)) {
                    this.CCIAAField = value;
                    this.RaisePropertyChanged("CCIAA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodiceFiscale {
            get {
                return this.CodiceFiscaleField;
            }
            set {
                if ((object.ReferenceEquals(this.CodiceFiscaleField, value) != true)) {
                    this.CodiceFiscaleField = value;
                    this.RaisePropertyChanged("CodiceFiscale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cognome {
            get {
                return this.CognomeField;
            }
            set {
                if ((object.ReferenceEquals(this.CognomeField, value) != true)) {
                    this.CognomeField = value;
                    this.RaisePropertyChanged("Cognome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataDiNascita {
            get {
                return this.DataDiNascitaField;
            }
            set {
                if ((object.ReferenceEquals(this.DataDiNascitaField, value) != true)) {
                    this.DataDiNascitaField = value;
                    this.RaisePropertyChanged("DataDiNascita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NREA {
            get {
                return this.NREAField;
            }
            set {
                if ((this.NREAField.Equals(value) != true)) {
                    this.NREAField = value;
                    this.RaisePropertyChanged("NREA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RagioneSociale {
            get {
                return this.RagioneSocialeField;
            }
            set {
                if ((object.ReferenceEquals(this.RagioneSocialeField, value) != true)) {
                    this.RagioneSocialeField = value;
                    this.RaisePropertyChanged("RagioneSociale");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValorizzazioneServizio", Namespace="http://comunicazionielettroniche.posteitaliane.it/camerali/data")]
    [System.SerializableAttribute()]
    public partial class ValorizzazioneServizio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdRichiestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ImportoNettoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Api.ServiceVol.ProdottoAmministrativo[] ProdottiAmministrativiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValutaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdRichiesta {
            get {
                return this.IdRichiestaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdRichiestaField, value) != true)) {
                    this.IdRichiestaField = value;
                    this.RaisePropertyChanged("IdRichiesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ImportoNetto {
            get {
                return this.ImportoNettoField;
            }
            set {
                if ((this.ImportoNettoField.Equals(value) != true)) {
                    this.ImportoNettoField = value;
                    this.RaisePropertyChanged("ImportoNetto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Api.ServiceVol.ProdottoAmministrativo[] ProdottiAmministrativi {
            get {
                return this.ProdottiAmministrativiField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdottiAmministrativiField, value) != true)) {
                    this.ProdottiAmministrativiField = value;
                    this.RaisePropertyChanged("ProdottiAmministrativi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Valuta {
            get {
                return this.ValutaField;
            }
            set {
                if ((object.ReferenceEquals(this.ValutaField, value) != true)) {
                    this.ValutaField = value;
                    this.RaisePropertyChanged("Valuta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Servizio", Namespace="http://comunicazionielettroniche.posteitaliane.it/camerali/data")]
    [System.SerializableAttribute()]
    public partial class Servizio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataConfermaRichiestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Api.ServiceVol.DatiOpzionali DatiOpzionaliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Api.ServiceVol.Destinatario DestinatarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Api.ServiceVol.Documento DocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdRichiestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Api.ServiceVol.Richiedente RichiedenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatoLavorazioneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Api.ServiceVol.ValorizzazioneServizio ValorizzazioneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataConfermaRichiesta {
            get {
                return this.DataConfermaRichiestaField;
            }
            set {
                if ((this.DataConfermaRichiestaField.Equals(value) != true)) {
                    this.DataConfermaRichiestaField = value;
                    this.RaisePropertyChanged("DataConfermaRichiesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Api.ServiceVol.DatiOpzionali DatiOpzionali {
            get {
                return this.DatiOpzionaliField;
            }
            set {
                if ((object.ReferenceEquals(this.DatiOpzionaliField, value) != true)) {
                    this.DatiOpzionaliField = value;
                    this.RaisePropertyChanged("DatiOpzionali");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Api.ServiceVol.Destinatario Destinatario {
            get {
                return this.DestinatarioField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinatarioField, value) != true)) {
                    this.DestinatarioField = value;
                    this.RaisePropertyChanged("Destinatario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Api.ServiceVol.Documento Documento {
            get {
                return this.DocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoField, value) != true)) {
                    this.DocumentoField = value;
                    this.RaisePropertyChanged("Documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdRichiesta {
            get {
                return this.IdRichiestaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdRichiestaField, value) != true)) {
                    this.IdRichiestaField = value;
                    this.RaisePropertyChanged("IdRichiesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Api.ServiceVol.Richiedente Richiedente {
            get {
                return this.RichiedenteField;
            }
            set {
                if ((object.ReferenceEquals(this.RichiedenteField, value) != true)) {
                    this.RichiedenteField = value;
                    this.RaisePropertyChanged("Richiedente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatoLavorazione {
            get {
                return this.StatoLavorazioneField;
            }
            set {
                if ((object.ReferenceEquals(this.StatoLavorazioneField, value) != true)) {
                    this.StatoLavorazioneField = value;
                    this.RaisePropertyChanged("StatoLavorazione");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Api.ServiceVol.ValorizzazioneServizio Valorizzazione {
            get {
                return this.ValorizzazioneField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorizzazioneField, value) != true)) {
                    this.ValorizzazioneField = value;
                    this.RaisePropertyChanged("Valorizzazione");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatoRichiesta", Namespace="http://comunicazionielettroniche.posteitaliane.it/camerali/data")]
    [System.SerializableAttribute()]
    public partial class StatoRichiesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescrizioneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdRichiestaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codice {
            get {
                return this.CodiceField;
            }
            set {
                if ((object.ReferenceEquals(this.CodiceField, value) != true)) {
                    this.CodiceField = value;
                    this.RaisePropertyChanged("Codice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descrizione {
            get {
                return this.DescrizioneField;
            }
            set {
                if ((object.ReferenceEquals(this.DescrizioneField, value) != true)) {
                    this.DescrizioneField = value;
                    this.RaisePropertyChanged("Descrizione");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdRichiesta {
            get {
                return this.IdRichiestaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdRichiestaField, value) != true)) {
                    this.IdRichiestaField = value;
                    this.RaisePropertyChanged("IdRichiesta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProdottoAmministrativo", Namespace="http://comunicazionielettroniche.posteitaliane.it/postaevo/data")]
    [System.SerializableAttribute()]
    public partial class ProdottoAmministrativo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodiceMaterialeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescrizioneCodiceMaterialeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ImportoNettoCodiceMaterialeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantitaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodiceMateriale {
            get {
                return this.CodiceMaterialeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodiceMaterialeField, value) != true)) {
                    this.CodiceMaterialeField = value;
                    this.RaisePropertyChanged("CodiceMateriale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescrizioneCodiceMateriale {
            get {
                return this.DescrizioneCodiceMaterialeField;
            }
            set {
                if ((object.ReferenceEquals(this.DescrizioneCodiceMaterialeField, value) != true)) {
                    this.DescrizioneCodiceMaterialeField = value;
                    this.RaisePropertyChanged("DescrizioneCodiceMateriale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ImportoNettoCodiceMateriale {
            get {
                return this.ImportoNettoCodiceMaterialeField;
            }
            set {
                if ((this.ImportoNettoCodiceMaterialeField.Equals(value) != true)) {
                    this.ImportoNettoCodiceMaterialeField = value;
                    this.RaisePropertyChanged("ImportoNettoCodiceMateriale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantita {
            get {
                return this.QuantitaField;
            }
            set {
                if ((this.QuantitaField.Equals(value) != true)) {
                    this.QuantitaField = value;
                    this.RaisePropertyChanged("Quantita");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Documento", Namespace="http://comunicazionielettroniche.posteitaliane.it/postaevo/data")]
    [System.SerializableAttribute()]
    public partial class Documento1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ContenutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstensioneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MD5Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Contenuto {
            get {
                return this.ContenutoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContenutoField, value) != true)) {
                    this.ContenutoField = value;
                    this.RaisePropertyChanged("Contenuto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estensione {
            get {
                return this.EstensioneField;
            }
            set {
                if ((object.ReferenceEquals(this.EstensioneField, value) != true)) {
                    this.EstensioneField = value;
                    this.RaisePropertyChanged("Estensione");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MD5 {
            get {
                return this.MD5Field;
            }
            set {
                if ((object.ReferenceEquals(this.MD5Field, value) != true)) {
                    this.MD5Field = value;
                    this.RaisePropertyChanged("MD5");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://comunicazionielettroniche.posteitaliane.it/camerali/service", ConfigurationName="ServiceVol.ICameraliService")]
    public interface ICameraliService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://comunicazionielettroniche.posteitaliane.it/camerali/service/ICameraliServi" +
            "ce/Invio", ReplyAction="http://comunicazionielettroniche.posteitaliane.it/camerali/service/ICameraliServi" +
            "ce/InvioResponse")]
        Api.ServiceVol.InvioResponse Invio(Api.ServiceVol.InvioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://comunicazionielettroniche.posteitaliane.it/camerali/service/ICameraliServi" +
            "ce/Invio", ReplyAction="http://comunicazionielettroniche.posteitaliane.it/camerali/service/ICameraliServi" +
            "ce/InvioResponse")]
        System.Threading.Tasks.Task<Api.ServiceVol.InvioResponse> InvioAsync(Api.ServiceVol.InvioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://comunicazionielettroniche.posteitaliane.it/camerali/service/ICameraliServi" +
            "ce/Conferma", ReplyAction="http://comunicazionielettroniche.posteitaliane.it/camerali/service/ICameraliServi" +
            "ce/ConfermaResponse")]
        Api.ServiceVol.ConfermaInvioResponse Conferma(Api.ServiceVol.ConfermaInvioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://comunicazionielettroniche.posteitaliane.it/camerali/service/ICameraliServi" +
            "ce/Conferma", ReplyAction="http://comunicazionielettroniche.posteitaliane.it/camerali/service/ICameraliServi" +
            "ce/ConfermaResponse")]
        System.Threading.Tasks.Task<Api.ServiceVol.ConfermaInvioResponse> ConfermaAsync(Api.ServiceVol.ConfermaInvioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://comunicazionielettroniche.posteitaliane.it/camerali/service/ICameraliServi" +
            "ce/RecuperaDocumento", ReplyAction="http://comunicazionielettroniche.posteitaliane.it/camerali/service/ICameraliServi" +
            "ce/RecuperaDocumentoResponse")]
        Api.ServiceVol.RecuperaDocumentoResponse RecuperaDocumento(Api.ServiceVol.RecuperaDocumentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://comunicazionielettroniche.posteitaliane.it/camerali/service/ICameraliServi" +
            "ce/RecuperaDocumento", ReplyAction="http://comunicazionielettroniche.posteitaliane.it/camerali/service/ICameraliServi" +
            "ce/RecuperaDocumentoResponse")]
        System.Threading.Tasks.Task<Api.ServiceVol.RecuperaDocumentoResponse> RecuperaDocumentoAsync(Api.ServiceVol.RecuperaDocumentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://comunicazionielettroniche.posteitaliane.it/camerali/service/ICameraliServi" +
            "ce/RecuperaServizio", ReplyAction="http://comunicazionielettroniche.posteitaliane.it/camerali/service/ICameraliServi" +
            "ce/RecuperaServizioResponse")]
        Api.ServiceVol.RecuperaServizioResponse RecuperaServizio(Api.ServiceVol.RecuperaServizioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://comunicazionielettroniche.posteitaliane.it/camerali/service/ICameraliServi" +
            "ce/RecuperaServizio", ReplyAction="http://comunicazionielettroniche.posteitaliane.it/camerali/service/ICameraliServi" +
            "ce/RecuperaServizioResponse")]
        System.Threading.Tasks.Task<Api.ServiceVol.RecuperaServizioResponse> RecuperaServizioAsync(Api.ServiceVol.RecuperaServizioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://comunicazionielettroniche.posteitaliane.it/camerali/service/ICameraliServi" +
            "ce/RecuperaStato", ReplyAction="http://comunicazionielettroniche.posteitaliane.it/camerali/service/ICameraliServi" +
            "ce/RecuperaStatoResponse")]
        Api.ServiceVol.RecuperaStatoResponse RecuperaStato(Api.ServiceVol.RecuperaStatoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://comunicazionielettroniche.posteitaliane.it/camerali/service/ICameraliServi" +
            "ce/RecuperaStato", ReplyAction="http://comunicazionielettroniche.posteitaliane.it/camerali/service/ICameraliServi" +
            "ce/RecuperaStatoResponse")]
        System.Threading.Tasks.Task<Api.ServiceVol.RecuperaStatoResponse> RecuperaStatoAsync(Api.ServiceVol.RecuperaStatoRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICameraliServiceChannel : Api.ServiceVol.ICameraliService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CameraliServiceClient : System.ServiceModel.ClientBase<Api.ServiceVol.ICameraliService>, Api.ServiceVol.ICameraliService {
        
        public CameraliServiceClient() {
        }
        
        public CameraliServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CameraliServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CameraliServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CameraliServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Api.ServiceVol.InvioResponse Invio(Api.ServiceVol.InvioRequest request) {
            return base.Channel.Invio(request);
        }
        
        public System.Threading.Tasks.Task<Api.ServiceVol.InvioResponse> InvioAsync(Api.ServiceVol.InvioRequest request) {
            return base.Channel.InvioAsync(request);
        }
        
        public Api.ServiceVol.ConfermaInvioResponse Conferma(Api.ServiceVol.ConfermaInvioRequest request) {
            return base.Channel.Conferma(request);
        }
        
        public System.Threading.Tasks.Task<Api.ServiceVol.ConfermaInvioResponse> ConfermaAsync(Api.ServiceVol.ConfermaInvioRequest request) {
            return base.Channel.ConfermaAsync(request);
        }
        
        public Api.ServiceVol.RecuperaDocumentoResponse RecuperaDocumento(Api.ServiceVol.RecuperaDocumentoRequest request) {
            return base.Channel.RecuperaDocumento(request);
        }
        
        public System.Threading.Tasks.Task<Api.ServiceVol.RecuperaDocumentoResponse> RecuperaDocumentoAsync(Api.ServiceVol.RecuperaDocumentoRequest request) {
            return base.Channel.RecuperaDocumentoAsync(request);
        }
        
        public Api.ServiceVol.RecuperaServizioResponse RecuperaServizio(Api.ServiceVol.RecuperaServizioRequest request) {
            return base.Channel.RecuperaServizio(request);
        }
        
        public System.Threading.Tasks.Task<Api.ServiceVol.RecuperaServizioResponse> RecuperaServizioAsync(Api.ServiceVol.RecuperaServizioRequest request) {
            return base.Channel.RecuperaServizioAsync(request);
        }
        
        public Api.ServiceVol.RecuperaStatoResponse RecuperaStato(Api.ServiceVol.RecuperaStatoRequest request) {
            return base.Channel.RecuperaStato(request);
        }
        
        public System.Threading.Tasks.Task<Api.ServiceVol.RecuperaStatoResponse> RecuperaStatoAsync(Api.ServiceVol.RecuperaStatoRequest request) {
            return base.Channel.RecuperaStatoAsync(request);
        }
    }
}
