//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bulletins
    {
        public int id { get; set; }
        public int namesId { get; set; }
        public string NumeroContoCorrente { get; set; }
        public string IntestatoA { get; set; }
        public string FormatoStampa { get; set; }
        public string Template { get; set; }
        public string AdditionalInfo { get; set; }
        public string IBAN { get; set; }
        public string CodiceCliente { get; set; }
        public decimal ImportoEuro { get; set; }
        public string EseguitoDaNominativo { get; set; }
        public string EseguitoDaIndirizzo { get; set; }
        public string EseguitoDaCAP { get; set; }
        public string EseguitoDaLocalita { get; set; }
        public string Causale { get; set; }
        public int BulletinType { get; set; }
        public int namesListsId { get; set; }
        public string Scadenza { get; set; }
        public string CBILL { get; set; }
        public Nullable<bool> PagoPA { get; set; }
        public string CodiciAvvisi { get; set; }
        public Nullable<bool> Pagato { get; set; }
        public Nullable<bool> Controllato { get; set; }
        public Nullable<System.DateTime> DataPagamento { get; set; }
    }
}
