//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    
    public enum currentState : int
    {
        inAttesa = 0,
        PresoInCarico = 1,
        InLavorazione = 2,
        Spedito = 3,
        Annullato = 4,
        ErroreSubmit = 5,
        ErroreValorizza = 6,
        ErroreConfirm = 7
    }
}
