//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DmProducts
    {
        public int id { get; set; }
        public string productName { get; set; }
        public string productDescription { get; set; }
        public string productDetails { get; set; }
        public Nullable<bool> active { get; set; }
    }
}
