//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GED
    {
        public int id { get; set; }
        public string fileName { get; set; }
        public int userId { get; set; }
        public string pathFile { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
