//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Listini
    {
        public int id { get; set; }
        public int productId { get; set; }
        public decimal creativita { get; set; }
        public decimal distrubuzione { get; set; }
        public decimal liste { get; set; }
        public decimal stampa500 { get; set; }
        public decimal stampa1000 { get; set; }
        public decimal stampa2000 { get; set; }
        public decimal stampa3000 { get; set; }
        public decimal stampa4000 { get; set; }
        public decimal stampa5000 { get; set; }
    
        public virtual Listini Listini1 { get; set; }
        public virtual Listini Listini2 { get; set; }
    }
}
