//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loghi
    {
        public int id { get; set; }
        public string name { get; set; }
        public string logo { get; set; }
        public int userId { get; set; }
        public Nullable<int> parentUserId { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
