//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Property> Property { get; set; }
        public virtual DbSet<operationFeatures> operationFeatures { get; set; }
        public virtual DbSet<Senders> Senders { get; set; }
        public virtual DbSet<Names> Names { get; set; }
        public virtual DbSet<Dm> Dm { get; set; }
        public virtual DbSet<Lists> Lists { get; set; }
        public virtual DbSet<NamesLists> NamesLists { get; set; }
        public virtual DbSet<NamesDm> NamesDm { get; set; }
        public virtual DbSet<DmConfigurations> DmConfigurations { get; set; }
        public virtual DbSet<DmProducts> DmProducts { get; set; }
        public virtual DbSet<Listini> Listini { get; set; }
        public virtual DbSet<SmsUsers> SmsUsers { get; set; }
        public virtual DbSet<SmsLists> SmsLists { get; set; }
        public virtual DbSet<SendersUsers> SendersUsers { get; set; }
        public virtual DbSet<Bulletins> Bulletins { get; set; }
        public virtual DbSet<Notifications> Notifications { get; set; }
        public virtual DbSet<TemporaryValidateTable> TemporaryValidateTable { get; set; }
        public virtual DbSet<Operations> Operations { get; set; }
        public virtual DbSet<UserPermits> UserPermits { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<GED> GED { get; set; }
    }
}
