//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NamesLists
    {
        public int id { get; set; }
        public string businessName { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string complementNames { get; set; }
        public string complementAddress { get; set; }
        public string dug { get; set; }
        public string address { get; set; }
        public string houseNumber { get; set; }
        public string cap { get; set; }
        public string city { get; set; }
        public string province { get; set; }
        public string state { get; set; }
        public int listId { get; set; }
        public string fileName { get; set; }
        public string fiscalCode { get; set; }
        public string mobile { get; set; }
        public Nullable<bool> noUse { get; set; }
        public Nullable<int> NREA { get; set; }
        public string codiceChiusura { get; set; }
        public Nullable<int> codiceDocumento { get; set; }
        public Nullable<int> tipoDocumento { get; set; }
        public string product { get; set; }
        public Nullable<System.DateTime> shipmentDate { get; set; }
        public Nullable<int> weight { get; set; }
        public Nullable<int> height { get; set; }
        public Nullable<int> length { get; set; }
        public Nullable<int> width { get; set; }
        public string contentText { get; set; }
        public string pathUrl { get; set; }
        public string additionalServices { get; set; }
        public Nullable<bool> senderFromContract { get; set; }
        public string contrassegno { get; set; }
        public string ritornoAlMittente { get; set; }
        public string assicurazione { get; set; }
        public Nullable<bool> sms { get; set; }
        public string testoSms { get; set; }
        public string logo { get; set; }
        public Nullable<bool> AvvisoRicevimentoDigitale { get; set; }
        public string pec { get; set; }
        public string cron { get; set; }
    
        public virtual Lists Lists { get; set; }
    }
}
