//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    
    public enum operationType : int
    {
        ROL = 1,
        LOL = 2,
        TELEGRAMMA = 3,
        MOL = 4,
        COL = 5,
        VOL = 6,
        PACCHI = 7,
        AGOL = 8
    }
}
