//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class operationFeatures
    {
        public int id { get; set; }
        public int operationId { get; set; }
        public string featureType { get; set; }
        public string featureValue { get; set; }
    
        public virtual Operations Operations { get; set; }
    }
}
