//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Operations()
        {
            this.Names = new HashSet<Names>();
            this.operationFeatures = new HashSet<operationFeatures>();
            this.Senders = new HashSet<Senders>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int userId { get; set; }
        public System.DateTime date { get; set; }
        public int operationType { get; set; }
        public bool demoOperation { get; set; }
        public bool complete { get; set; }
        public Nullable<int> userParentId { get; set; }
        public bool areaTestOperation { get; set; }
        public int operationPriority { get; set; }
        public Nullable<bool> lottoCompleto { get; set; }
        public Nullable<bool> lotto { get; set; }
        public Nullable<bool> formatoSpeciale { get; set; }
        public Nullable<bool> formatoSpecialeInviato { get; set; }
        public Nullable<bool> error { get; set; }
        public string errorMessage { get; set; }
        public string csvFileName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Names> Names { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<operationFeatures> operationFeatures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Senders> Senders { get; set; }
        public virtual Users Users { get; set; }
    }
}
