//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    
    public enum products : int
    {
        CartoPlus10SC = 1,
        CartoPlusLGRidotto = 2,
        CartoPlusLG = 3,
        CartolinaA5 = 4,
        CartolinaA6 = 5
    }
}
