//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelectItemFromProducts
    {
        public int productType { get; set; }
        public int selectedQuantityInvio { get; set; }
        public int chunkedByInvio { get; set; }
        public int selectedQuantityValorizza { get; set; }
        public int chunkedByValorizza { get; set; }
        public int selectedQuantityConferma { get; set; }
        public int chunkedByConferma { get; set; }
        public int startHour { get; set; }
        public int endHour { get; set; }
        public Nullable<int> id { get; set; }
    }
}
