//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemporaryValidateTable
    {
        public System.Guid id { get; set; }
        public string sessionId { get; set; }
        public bool valid { get; set; }
        public int userId { get; set; }
        public int totalNames { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
