//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.GED1 = new HashSet<GED>();
            this.Lists = new HashSet<Lists>();
            this.Loghi = new HashSet<Loghi>();
            this.Logs = new HashSet<Logs>();
            this.Operations = new HashSet<Operations>();
            this.SendersUsers = new HashSet<SendersUsers>();
            this.TemporaryValidateTable = new HashSet<TemporaryValidateTable>();
            this.UserPermits = new HashSet<UserPermits>();
        }
    
        public int id { get; set; }
        public string usernamePoste { get; set; }
        public string pwdPoste { get; set; }
        public int porpertyId { get; set; }
        public string name { get; set; }
        public string lastName { get; set; }
        public int userType { get; set; }
        public string email { get; set; }
        public System.Guid guidUser { get; set; }
        public string businessName { get; set; }
        public string baseUrl { get; set; }
        public string pwd { get; set; }
        public string address { get; set; }
        public string cap { get; set; }
        public string city { get; set; }
        public string province { get; set; }
        public string mobile { get; set; }
        public bool demoUser { get; set; }
        public int parentId { get; set; }
        public string sendersId { get; set; }
        public string usernamePosteAreaTest { get; set; }
        public string pwdPosteAreaTest { get; set; }
        public bool areaTestUser { get; set; }
        public Nullable<bool> mol { get; set; }
        public string CodiceContrattoMOL { get; set; }
        public string CodiceContrattoCOL { get; set; }
        public Nullable<bool> changePwd { get; set; }
        public int userPriority { get; set; }
        public Nullable<bool> col { get; set; }
        public string logoPA { get; set; }
        public string denominazioneEntePA { get; set; }
        public string infoEntePA { get; set; }
        public string settoreEntePA { get; set; }
        public string codiceFiscaleEntePA { get; set; }
        public Nullable<bool> attivoPA { get; set; }
        public Nullable<bool> downloadFile { get; set; }
        public string piva { get; set; }
        public string usernameGED { get; set; }
        public string passwordGED { get; set; }
        public Nullable<bool> GED { get; set; }
        public Nullable<bool> master { get; set; }
        public Nullable<int> collegatoMasterId { get; set; }
        public Nullable<bool> conciliazioneBollettini { get; set; }
        public Nullable<bool> abilitato { get; set; }
        public Nullable<bool> pacchi { get; set; }
        public string usernamePacchi { get; set; }
        public string passwordPacchi { get; set; }
        public string centerCostPacchi { get; set; }
        public Nullable<bool> sms { get; set; }
        public Nullable<int> senderPkgId { get; set; }
        public Nullable<bool> downloadableFileFromPage { get; set; }
        public string fiscalCode { get; set; }
        public string emailPec { get; set; }
        public Nullable<bool> hidePrice { get; set; }
        public Nullable<bool> sso { get; set; }
        public Nullable<System.DateTime> expireDate { get; set; }
        public Nullable<System.DateTime> insertDate { get; set; }
        public Nullable<bool> RendicontazioneFatture { get; set; }
        public string CodiceContrattoAGOLM { get; set; }
        public string CodiceContrattoAGOLB { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GED> GED1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lists> Lists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loghi> Loghi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Logs> Logs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operations> Operations { get; set; }
        public virtual Property Property { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SendersUsers> SendersUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemporaryValidateTable> TemporaryValidateTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPermits> UserPermits { get; set; }
    }
}
