//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Dm = new HashSet<Dm>();
            this.Lists = new HashSet<Lists>();
            this.Operations = new HashSet<Operations>();
            this.SendersUsers = new HashSet<SendersUsers>();
            this.SmsUsers = new HashSet<SmsUsers>();
            this.TemporaryValidateTable = new HashSet<TemporaryValidateTable>();
            this.UserPermits = new HashSet<UserPermits>();
            this.GED1 = new HashSet<GED>();
        }
    
        public int id { get; set; }
        public string usernamePoste { get; set; }
        public string pwdPoste { get; set; }
        public int porpertyId { get; set; }
        public string name { get; set; }
        public string lastName { get; set; }
        public int userType { get; set; }
        public string email { get; set; }
        public System.Guid guidUser { get; set; }
        public string businessName { get; set; }
        public string baseUrl { get; set; }
        public string pwd { get; set; }
        public string address { get; set; }
        public string cap { get; set; }
        public string city { get; set; }
        public string province { get; set; }
        public string mobile { get; set; }
        public bool demoUser { get; set; }
        public int parentId { get; set; }
        public string sendersId { get; set; }
        public string usernamePosteAreaTest { get; set; }
        public string pwdPosteAreaTest { get; set; }
        public bool areaTestUser { get; set; }
        public Nullable<bool> mol { get; set; }
        public string CodiceContrattoMOL { get; set; }
        public string CodiceContrattoCOL { get; set; }
        public Nullable<bool> changePwd { get; set; }
        public int userPriority { get; set; }
        public Nullable<bool> col { get; set; }
        public string logoPA { get; set; }
        public string denominazioneEntePA { get; set; }
        public string infoEntePA { get; set; }
        public string settoreEntePA { get; set; }
        public string codiceFiscaleEntePA { get; set; }
        public Nullable<bool> attivoPA { get; set; }
        public Nullable<bool> downloadFile { get; set; }
        public string piva { get; set; }
        public string usernameGED { get; set; }
        public string passwordGED { get; set; }
        public Nullable<bool> GED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dm> Dm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lists> Lists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operations> Operations { get; set; }
        public virtual Property Property { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SendersUsers> SendersUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SmsUsers> SmsUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemporaryValidateTable> TemporaryValidateTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPermits> UserPermits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GED> GED1 { get; set; }
    }
}
