//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPermits
    {
        public int id { get; set; }
        public int userId { get; set; }
        public bool rol { get; set; }
        public bool lol { get; set; }
        public bool tol { get; set; }
        public bool mol { get; set; }
        public bool col { get; set; }
        public bool pec { get; set; }
        public bool pacchi { get; set; }
        public bool sms { get; set; }
        public bool marketing { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
