//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.ServiceGED {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ais.it/wsdl", ConfigurationName="ServiceGED.DirectSearchIF")]
    public interface DirectSearchIF {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        int available();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<int> availableAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void close();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task closeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        [return: System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")]
        byte[] getDocument(string[] arrayOfString_1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        [return: System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")]
        System.Threading.Tasks.Task<byte[]> getDocumentAsync(string[] arrayOfString_1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void open(string[] arrayOfString_1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task openAsync(string[] arrayOfString_1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        [return: System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")]
        byte[] read(int int_1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        [return: System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")]
        System.Threading.Tasks.Task<byte[]> readAsync(int int_1);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DirectSearchIFChannel : Api.ServiceGED.DirectSearchIF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DirectSearchIFClient : System.ServiceModel.ClientBase<Api.ServiceGED.DirectSearchIF>, Api.ServiceGED.DirectSearchIF {
        
        public DirectSearchIFClient() {
        }
        
        public DirectSearchIFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DirectSearchIFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DirectSearchIFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DirectSearchIFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int available() {
            return base.Channel.available();
        }
        
        public System.Threading.Tasks.Task<int> availableAsync() {
            return base.Channel.availableAsync();
        }
        
        public void close() {
            base.Channel.close();
        }
        
        public System.Threading.Tasks.Task closeAsync() {
            return base.Channel.closeAsync();
        }
        
        public byte[] getDocument(string[] arrayOfString_1) {
            return base.Channel.getDocument(arrayOfString_1);
        }
        
        public System.Threading.Tasks.Task<byte[]> getDocumentAsync(string[] arrayOfString_1) {
            return base.Channel.getDocumentAsync(arrayOfString_1);
        }
        
        public void open(string[] arrayOfString_1) {
            base.Channel.open(arrayOfString_1);
        }
        
        public System.Threading.Tasks.Task openAsync(string[] arrayOfString_1) {
            return base.Channel.openAsync(arrayOfString_1);
        }
        
        public byte[] read(int int_1) {
            return base.Channel.read(int_1);
        }
        
        public System.Threading.Tasks.Task<byte[]> readAsync(int int_1) {
            return base.Channel.readAsync(int_1);
        }
    }
}
